version: '3.5'

services: 
    backend:
      image: backend
      ports:
        - 8000:8000
      environment:
      - REDIS=redis
    redis:
      image: redis
    frontend:
      image: frontend
      ports: 
      - 5000:5000