version: '3.5'

services: 
  backend:
    build: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    volumes:
    - model:/src/model
    ports:
    - 5000:5000
  frontend:
    build: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    ports:
    - 3000:3000
  training:
    build: https://github.com/docker-hy/ml-kurkkumopo-training.git
    volumes:
     - imgs:/src/imgs
     - data:/src/data
     - model:/src/model

volumes:
  model:
  imgs:
  data: